image: gradle:alpine

stages:
  - build
  - test
  
before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache assemble

test:
  stage: test
  script: gradle check
